#spring:
# datasource:
#   username: root
#   password: root
#    url: jdbc:mysql://localhost:3306/billing
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties.hibernate.dialect:org.hibernate.dialect.MYSQL5Dialect